### ISSUE TITLE
Section on object is handled as array

### ISSUE THREAD

**Issue by milung** [StubbleOrg/Stubble.Extensions.JsonNet#9] opened 2019-08-09 12:57 UTC
See PR #8. 

If the section  with object but not array is used, it is incorrectly interpreted as section with array. The reason is that section renderer cannot recognize it as IDictionary, but while JObject implements both IDictionary<string, JToken> and IEnumerable. Proposed fix is by converting this special case into Dictionary of properties.

**Comment by Romanx** [comment] 2019-08-11 12:10
Hi there,

Thanks very much for opening this issue. You're right it seems to be related to how we identity that the section can be iterated on and it instead tries to loop through all the members in the `JObject`. We have a method of filtering types we don't want the standard logic to apply which we do for both `string` and `IDictionary`.

You can override the section blacklist by using the `SetSectionBlacklistTypes` method on the builder however this doesn't allow you to just add to the blacklist which we've added to Stubble here: StubbleOrg/Stubble#70

With this change we can add to the extension the ability to blacklist `IDictionary<string, JToken>` which will make the logic work as intended

**Comment by Romanx** [comment] 2019-08-11 12:49
@milung Thanks to your report and contribution of a fix for this. The updated code has been released on nuget in version `v1.2.3`

Please feel free to open another issue you if you have any other problems. Thank you for using Stubble! 👍

**Closed as completed by Romanx** 2019-08-11 12:49 UTC
Labels: bug
